networks:
    inception:
        name: inception

secrets:
    wp_admin_pw:
        file: ../secrets/wp_admin_password.txt
    db_pw:
        file: ../secrets/db_password.txt
    db_root_pw:
        file: ../secrets/db_root_password.txt

services:
    nginx:
        container_name: nginx
        image: nginx:wdegraf42
        build: ./requirements/nginx
        ports:
          - "443:443"
        depends_on:
          - wordpress
        volumes:
          - /home/wdegraf/data/wordpress:/var/www/html
        networks:
          - inception
        env_file:
          - .env
        restart: always

    wordpress:
        container_name: wordpress
        image: wordpress:wdegraf42
        build: ./requirements/wordpress/.
        depends_on:
          - mariadb
        volumes:
          - /home/wdegraf/data/wordpress:/var/www/html
        env_file:
          - .env
        networks:
          - inception
        restart: always
        secrets:
          - db_pw
          - db_root_pw
          - wp_admin_pw

    mariadb:
        container_name: mariadb
        image: mariadb:wdegraf42
        build: ./requirements/mariadb/.
        volumes:
          - /home/wdegraf/data/mariadb:/var/lib/mysql
        env_file:
          - .env
        networks:
          - inception
        restart: always
        secrets:
          - db_pw
          - db_root_pw
